import { resendClient, sender } from "../lib/resend.js";
import { createWelcomeEmailTemplate } from "../emails/emailTemplates.js";

export const sendWelcomeEmail = async (email, name, clientURL) => {
  const { data, error } = await resendClient.emails.send({
    from: `${sender.name} <${sender.email}>`,
    to: email,
    subject: "Welcome to Chatroom!",
    html: createWelcomeEmailTemplate(name, clientURL),
  });

  if (error) {
    console.error("Error sending welcome email:", error);
    throw new Error("Failed to send welcome email");
  }

  console.log("Welcome Email sent successfully", data);
};
// 1. The function sendWelcomeEmail is an asynchronous function that takes three parameters: email, name, and clientURL.
// 2. It uses the resendClient to send an email by calling the emails.send method.
// 3. The email is sent from a formatted string that includes the sender's name and email address.
// 4. The recipient of the email is specified by the email parameter.
// 5. The subject of the email is set to "Welcome to Chatroom!".
// 6. The HTML content of the email is generated by calling the createWelcomeEmailTemplate function, passing in the name and clientURL parameters.
// 7. After attempting to send the email, the function checks if there was an error.
// 8. If there is an error, it logs the error message to the console and throws a new Error indicating that the welcome email failed to send.
// 9. If the email is sent successfully, it logs a success message along with the data returned from the email sending operation.
